dist: trusty
sudo: required

language: generic

before_install:
    # Required by Buildozer Android
    # https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-12-04-64bit
    - sudo apt-get update -q
    - sudo apt-get install build-essential ccache git lib32z1 lib32bz2-1.0 libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386
    # Required by Kivy
    # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
    - sudo apt-get install python-pip build-essential git python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

install:
    - sudo pip install coveralls

env:
    global:
        - COVERALLS_PARALLEL=true
    matrix:
        - SCRIPT_COMMAND="./travis/script_linux.sh"
        - SCRIPT_COMMAND="./travis/script_android.sh"

script:
    # runs in parallel
    - (eval "$SCRIPT_COMMAND")

after_success:
    - coveralls
